#!/bin/sh

userresources=$XDG_CONFIG_HOME/.Xresources
usermodmap=$XDG_CONFIG_HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xmodmap -e 'keycode 66 = Control_L' 
xmodmap -e 'clear Lock'             
xmodmap -e 'add Control = Control_L'

xrandr --output DP-1 --mode 2560x1440
xrandr --output HDMI-0 --mode 2560x1440
xrandr --output DP-1 --same-as HDMI-0

exec i3
