user: cyan
group: magenta
permission:
  read: dark_green
  write: dark_yellow
  exec: dark_red
  exec-sticky: 5
  no-access: 245
date:
  hour-old: 40
  day-old: 42
  older: 36
size:
  none: yellow
  small: yellow
  medium: yellow
  large: yellow
inode:
  valid: dark_cyan
  invalid: dark_red
links:
  valid: dark_cyan
  invalid: dark_red
tree-edge: 245
